name: Code Review Automation

on:
  # Exécution manuelle depuis l'interface GitHub
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'URL du dépôt GitHub à analyser'
        required: true
        type: string
      target_path:
        description: 'Nom du fichier ou du dossier à examiner'
        required: true
        type: string
  
  # Exécution programmée (une fois par jour à minuit)
  schedule:
    - cron: '0 0 * * *'
  
  # Exécution lors d'une ouverture/mise à jour de pull request (optionnel)
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.py'  # Limiter aux fichiers Python

jobs:
  review_code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run code review on scheduled or manual trigger
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_API_KEY: ${{ secrets.GITHUB_API_KEY }}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            python auto_review.py --repo "${{ github.event.inputs.repo_url }}" --target "${{ github.event.inputs.target_path }}"
          else
            # Pour l'exécution programmée, utilisez un dépôt par défaut ou lisez-le depuis un fichier de configuration
            python auto_review.py --config config.json
          fi
      
      - name: Run code review on pull request
        if: github.event_name == 'pull_request'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_API_KEY: ${{ secrets.GITHUB_API_KEY }}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python pr_review.py --repo "${{ github.repository }}" --pr $PR_NUMBER
